# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 646)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(965, 625))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.getFile_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getFile_btn.sizePolicy().hasHeightForWidth())
        self.getFile_btn.setSizePolicy(sizePolicy)
        self.getFile_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.getFile_btn.setObjectName("getFile_btn")
        self.gridLayout_2.addWidget(self.getFile_btn, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.time_initial_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_initial_label.sizePolicy().hasHeightForWidth())
        self.time_initial_label.setSizePolicy(sizePolicy)
        self.time_initial_label.setMinimumSize(QtCore.QSize(0, 10))
        self.time_initial_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.time_initial_label.setObjectName("time_initial_label")
        self.gridLayout_4.addWidget(self.time_initial_label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 1, 1, 1)
        self.time_initial = QtWidgets.QSpinBox(self.groupBox)
        self.time_initial.setMaximum(1000000)
        self.time_initial.setObjectName("time_initial")
        self.gridLayout_4.addWidget(self.time_initial, 1, 0, 1, 1)
        self.time_initial_stop = QtWidgets.QSpinBox(self.groupBox)
        self.time_initial_stop.setMaximum(1000000000)
        self.time_initial_stop.setObjectName("time_initial_stop")
        self.gridLayout_4.addWidget(self.time_initial_stop, 1, 1, 1, 1)
        self.time_final_label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_final_label.sizePolicy().hasHeightForWidth())
        self.time_final_label.setSizePolicy(sizePolicy)
        self.time_final_label.setObjectName("time_final_label")
        self.gridLayout_4.addWidget(self.time_final_label, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 1, 1, 1)
        self.time_final = QtWidgets.QSpinBox(self.groupBox)
        self.time_final.setMaximum(1000000)
        self.time_final.setObjectName("time_final")
        self.gridLayout_4.addWidget(self.time_final, 3, 0, 1, 1)
        self.time_final_stop = QtWidgets.QSpinBox(self.groupBox)
        self.time_final_stop.setMaximum(1000000000)
        self.time_final_stop.setObjectName("time_final_stop")
        self.gridLayout_4.addWidget(self.time_final_stop, 3, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 4, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 2)
        self.process_btn = QtWidgets.QPushButton(self.centralwidget)
        self.process_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.process_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.process_btn.setObjectName("process_btn")
        self.gridLayout_2.addWidget(self.process_btn, 1, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.MplWidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.MplWidget.setObjectName("MplWidget")
        self.verticalLayout_5.addWidget(self.MplWidget)
        self.MplWidget_D = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget_D.sizePolicy().hasHeightForWidth())
        self.MplWidget_D.setSizePolicy(sizePolicy)
        self.MplWidget_D.setObjectName("MplWidget_D")
        self.verticalLayout_5.addWidget(self.MplWidget_D)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OPENQCM NEXT DATA VIEW V-02-dev"))
        self.getFile_btn.setText(_translate("MainWindow", "GET .CSV DATA FILE"))
        self.groupBox.setTitle(_translate("MainWindow", "Frequency - Dissipation Variation"))
        self.time_initial_label.setText(_translate("MainWindow", "Inital Time"))
        self.label_4.setText(_translate("MainWindow", "Duration (sec)"))
        self.time_final_label.setText(_translate("MainWindow", "Final Time"))
        self.label_5.setText(_translate("MainWindow", "Duration (sec)"))
        self.process_btn.setText(_translate("MainWindow", "PROCESS"))

from openQCM.data_view.mplwidget import MplWidget
