# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_designer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 894)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 2, 1, 1)
        self.time_initial_stop = QtWidgets.QSpinBox(self.centralwidget)
        self.time_initial_stop.setMaximum(1000000000)
        self.time_initial_stop.setObjectName("time_initial_stop")
        self.gridLayout_2.addWidget(self.time_initial_stop, 4, 2, 1, 1)
        self.time_final = QtWidgets.QSpinBox(self.centralwidget)
        self.time_final.setMaximum(1000000)
        self.time_final.setObjectName("time_final")
        self.gridLayout_2.addWidget(self.time_final, 6, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 1, 3, 6, 1)
        self.time_initial = QtWidgets.QSpinBox(self.centralwidget)
        self.time_initial.setMaximum(1000000)
        self.time_initial.setObjectName("time_initial")
        self.gridLayout_2.addWidget(self.time_initial, 4, 1, 1, 1)
        self.time_final_label = QtWidgets.QLabel(self.centralwidget)
        self.time_final_label.setObjectName("time_final_label")
        self.gridLayout_2.addWidget(self.time_final_label, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.time_initial_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_initial_label.sizePolicy().hasHeightForWidth())
        self.time_initial_label.setSizePolicy(sizePolicy)
        self.time_initial_label.setMinimumSize(QtCore.QSize(0, 10))
        self.time_initial_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.time_initial_label.setObjectName("time_initial_label")
        self.gridLayout_2.addWidget(self.time_initial_label, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 2, 1, 1)
        self.time_final_stop = QtWidgets.QSpinBox(self.centralwidget)
        self.time_final_stop.setMaximum(1000000000)
        self.time_final_stop.setObjectName("time_final_stop")
        self.gridLayout_2.addWidget(self.time_final_stop, 6, 2, 1, 1)
        self.getFile_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getFile_btn.sizePolicy().hasHeightForWidth())
        self.getFile_btn.setSizePolicy(sizePolicy)
        self.getFile_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.getFile_btn.setObjectName("getFile_btn")
        self.gridLayout_2.addWidget(self.getFile_btn, 1, 0, 1, 3)
        self.process_btn = QtWidgets.QPushButton(self.centralwidget)
        self.process_btn.setMinimumSize(QtCore.QSize(0, 40))
        self.process_btn.setMaximumSize(QtCore.QSize(16777215, 40))
        self.process_btn.setObjectName("process_btn")
        self.gridLayout_2.addWidget(self.process_btn, 2, 0, 1, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.MplWidget_D = MplWidget(self.centralwidget)
        self.MplWidget_D.setObjectName("MplWidget_D")
        self.gridLayout.addWidget(self.MplWidget_D, 5, 0, 3, 1)
        self.MplWidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout.addWidget(self.MplWidget, 2, 0, 3, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OPENQCM NEXT DATA VIEW V-02-dev"))
        self.label_3.setText(_translate("MainWindow", "FINAL STATE"))
        self.label_4.setText(_translate("MainWindow", "Initial Time Stop"))
        self.time_final_label.setText(_translate("MainWindow", "Final Time Start "))
        self.label.setText(_translate("MainWindow", "Output"))
        self.time_initial_label.setText(_translate("MainWindow", "Inital Time Start"))
        self.label_2.setText(_translate("MainWindow", "INITIAL STATE"))
        self.label_5.setText(_translate("MainWindow", "Final Time Stop"))
        self.getFile_btn.setText(_translate("MainWindow", "GET .CSV DATA FILE"))
        self.process_btn.setText(_translate("MainWindow", "PROCESS"))

from openQCM.data_view.mplwidget import MplWidget
