# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_new_mac_31.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 980)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../../.designer/backup/favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_data = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_data.setObjectName("groupBox_data")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_data)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.F9 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F9.sizePolicy().hasHeightForWidth())
        self.F9.setSizePolicy(sizePolicy)
        self.F9.setObjectName("F9")
        self.gridLayout_7.addWidget(self.F9, 4, 3, 1, 1)
        self.D7 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7.sizePolicy().hasHeightForWidth())
        self.D7.setSizePolicy(sizePolicy)
        self.D7.setObjectName("D7")
        self.gridLayout_7.addWidget(self.D7, 3, 5, 1, 1)
        self.D5 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5.sizePolicy().hasHeightForWidth())
        self.D5.setSizePolicy(sizePolicy)
        self.D5.setObjectName("D5")
        self.gridLayout_7.addWidget(self.D5, 2, 5, 1, 1)
        self.D9 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D9.sizePolicy().hasHeightForWidth())
        self.D9.setSizePolicy(sizePolicy)
        self.D9.setObjectName("D9")
        self.gridLayout_7.addWidget(self.D9, 4, 5, 1, 1)
        self.label_D5 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D5.sizePolicy().hasHeightForWidth())
        self.label_D5.setSizePolicy(sizePolicy)
        self.label_D5.setTextFormat(QtCore.Qt.RichText)
        self.label_D5.setObjectName("label_D5")
        self.gridLayout_7.addWidget(self.label_D5, 2, 4, 1, 1)
        self.label_D7 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D7.sizePolicy().hasHeightForWidth())
        self.label_D7.setSizePolicy(sizePolicy)
        self.label_D7.setTextFormat(QtCore.Qt.RichText)
        self.label_D7.setObjectName("label_D7")
        self.gridLayout_7.addWidget(self.label_D7, 3, 4, 1, 1)
        self.label_D9 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D9.sizePolicy().hasHeightForWidth())
        self.label_D9.setSizePolicy(sizePolicy)
        self.label_D9.setObjectName("label_D9")
        self.gridLayout_7.addWidget(self.label_D9, 4, 4, 1, 1)
        self.label_D0 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D0.sizePolicy().hasHeightForWidth())
        self.label_D0.setSizePolicy(sizePolicy)
        self.label_D0.setTextFormat(QtCore.Qt.RichText)
        self.label_D0.setObjectName("label_D0")
        self.gridLayout_7.addWidget(self.label_D0, 0, 4, 1, 1)
        self.F3 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3.sizePolicy().hasHeightForWidth())
        self.F3.setSizePolicy(sizePolicy)
        self.F3.setObjectName("F3")
        self.gridLayout_7.addWidget(self.F3, 1, 3, 1, 1)
        self.label_F9_col = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F9_col.sizePolicy().hasHeightForWidth())
        self.label_F9_col.setSizePolicy(sizePolicy)
        self.label_F9_col.setText("")
        self.label_F9_col.setObjectName("label_F9_col")
        self.gridLayout_7.addWidget(self.label_F9_col, 4, 0, 1, 1)
        self.F0 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F0.sizePolicy().hasHeightForWidth())
        self.F0.setSizePolicy(sizePolicy)
        self.F0.setObjectName("F0")
        self.gridLayout_7.addWidget(self.F0, 0, 3, 1, 1)
        self.label_F5 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F5.sizePolicy().hasHeightForWidth())
        self.label_F5.setSizePolicy(sizePolicy)
        self.label_F5.setTextFormat(QtCore.Qt.RichText)
        self.label_F5.setObjectName("label_F5")
        self.gridLayout_7.addWidget(self.label_F5, 2, 1, 1, 1)
        self.label_F7_col = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F7_col.sizePolicy().hasHeightForWidth())
        self.label_F7_col.setSizePolicy(sizePolicy)
        self.label_F7_col.setText("")
        self.label_F7_col.setObjectName("label_F7_col")
        self.gridLayout_7.addWidget(self.label_F7_col, 3, 0, 1, 1)
        self.label_F5_col = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F5_col.sizePolicy().hasHeightForWidth())
        self.label_F5_col.setSizePolicy(sizePolicy)
        self.label_F5_col.setText("")
        self.label_F5_col.setObjectName("label_F5_col")
        self.gridLayout_7.addWidget(self.label_F5_col, 2, 0, 1, 1)
        self.label_F3_col = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F3_col.sizePolicy().hasHeightForWidth())
        self.label_F3_col.setSizePolicy(sizePolicy)
        self.label_F3_col.setText("")
        self.label_F3_col.setObjectName("label_F3_col")
        self.gridLayout_7.addWidget(self.label_F3_col, 1, 0, 1, 1)
        self.label_F0_col = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F0_col.sizePolicy().hasHeightForWidth())
        self.label_F0_col.setSizePolicy(sizePolicy)
        self.label_F0_col.setText("")
        self.label_F0_col.setObjectName("label_F0_col")
        self.gridLayout_7.addWidget(self.label_F0_col, 0, 0, 1, 1)
        self.D3 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3.sizePolicy().hasHeightForWidth())
        self.D3.setSizePolicy(sizePolicy)
        self.D3.setObjectName("D3")
        self.gridLayout_7.addWidget(self.D3, 1, 5, 1, 1)
        self.label_D3 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D3.sizePolicy().hasHeightForWidth())
        self.label_D3.setSizePolicy(sizePolicy)
        self.label_D3.setTextFormat(QtCore.Qt.RichText)
        self.label_D3.setObjectName("label_D3")
        self.gridLayout_7.addWidget(self.label_D3, 1, 4, 1, 1)
        self.label_F0 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F0.sizePolicy().hasHeightForWidth())
        self.label_F0.setSizePolicy(sizePolicy)
        self.label_F0.setTextFormat(QtCore.Qt.RichText)
        self.label_F0.setScaledContents(False)
        self.label_F0.setObjectName("label_F0")
        self.gridLayout_7.addWidget(self.label_F0, 0, 1, 1, 1)
        self.label_F3 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F3.sizePolicy().hasHeightForWidth())
        self.label_F3.setSizePolicy(sizePolicy)
        self.label_F3.setTextFormat(QtCore.Qt.RichText)
        self.label_F3.setObjectName("label_F3")
        self.gridLayout_7.addWidget(self.label_F3, 1, 1, 1, 1)
        self.F5 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5.sizePolicy().hasHeightForWidth())
        self.F5.setSizePolicy(sizePolicy)
        self.F5.setObjectName("F5")
        self.gridLayout_7.addWidget(self.F5, 2, 3, 1, 1)
        self.label_F7 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F7.sizePolicy().hasHeightForWidth())
        self.label_F7.setSizePolicy(sizePolicy)
        self.label_F7.setTextFormat(QtCore.Qt.RichText)
        self.label_F7.setObjectName("label_F7")
        self.gridLayout_7.addWidget(self.label_F7, 3, 1, 1, 1)
        self.label_F9 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F9.sizePolicy().hasHeightForWidth())
        self.label_F9.setSizePolicy(sizePolicy)
        self.label_F9.setTextFormat(QtCore.Qt.RichText)
        self.label_F9.setObjectName("label_F9")
        self.gridLayout_7.addWidget(self.label_F9, 4, 1, 1, 1)
        self.F7 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F7.sizePolicy().hasHeightForWidth())
        self.F7.setSizePolicy(sizePolicy)
        self.F7.setObjectName("F7")
        self.gridLayout_7.addWidget(self.F7, 3, 3, 1, 1)
        self.D0 = QtWidgets.QLabel(self.groupBox_data)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D0.sizePolicy().hasHeightForWidth())
        self.D0.setSizePolicy(sizePolicy)
        self.D0.setObjectName("D0")
        self.gridLayout_7.addWidget(self.D0, 0, 5, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_data, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(45, 45))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("favicon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_2.raise_()
        self.label.raise_()
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(250, 190))
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Temperature_state = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Temperature_state.sizePolicy().hasHeightForWidth())
        self.label_Temperature_state.setSizePolicy(sizePolicy)
        self.label_Temperature_state.setObjectName("label_Temperature_state")
        self.gridLayout_4.addWidget(self.label_Temperature_state, 0, 0, 1, 4)
        self.doubleSpinBox_Temperature = QtWidgets.QDoubleSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Temperature.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Temperature.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Temperature.setDecimals(0)
        self.doubleSpinBox_Temperature.setMinimum(5.0)
        self.doubleSpinBox_Temperature.setMaximum(45.0)
        self.doubleSpinBox_Temperature.setProperty("value", 25.0)
        self.doubleSpinBox_Temperature.setObjectName("doubleSpinBox_Temperature")
        self.gridLayout_4.addWidget(self.doubleSpinBox_Temperature, 3, 2, 1, 2)
        self.indicator_temperature = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indicator_temperature.sizePolicy().hasHeightForWidth())
        self.indicator_temperature.setSizePolicy(sizePolicy)
        self.indicator_temperature.setObjectName("indicator_temperature")
        self.gridLayout_4.addWidget(self.indicator_temperature, 4, 2, 1, 2)
        self.pButton_Temperature_Set = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Temperature_Set.sizePolicy().hasHeightForWidth())
        self.pButton_Temperature_Set.setSizePolicy(sizePolicy)
        self.pButton_Temperature_Set.setObjectName("pButton_Temperature_Set")
        self.gridLayout_4.addWidget(self.pButton_Temperature_Set, 3, 0, 1, 2)
        self.label_Temperature = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Temperature.sizePolicy().hasHeightForWidth())
        self.label_Temperature.setSizePolicy(sizePolicy)
        self.label_Temperature.setObjectName("label_Temperature")
        self.gridLayout_4.addWidget(self.label_Temperature, 4, 0, 1, 2)
        self.pButton_Tswitch_ON = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Tswitch_ON.sizePolicy().hasHeightForWidth())
        self.pButton_Tswitch_ON.setSizePolicy(sizePolicy)
        self.pButton_Tswitch_ON.setObjectName("pButton_Tswitch_ON")
        self.gridLayout_4.addWidget(self.pButton_Tswitch_ON, 1, 0, 1, 2)
        self.pButton_TEC_Reset = QtWidgets.QPushButton(self.tab)
        self.pButton_TEC_Reset.setObjectName("pButton_TEC_Reset")
        self.gridLayout_4.addWidget(self.pButton_TEC_Reset, 2, 0, 1, 4)
        self.pButton_Tswitch_OFF = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Tswitch_OFF.sizePolicy().hasHeightForWidth())
        self.pButton_Tswitch_OFF.setSizePolicy(sizePolicy)
        self.pButton_Tswitch_OFF.setObjectName("pButton_Tswitch_OFF")
        self.gridLayout_4.addWidget(self.pButton_Tswitch_OFF, 1, 2, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_6.addWidget(self.line_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pButton_PID_Set = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_PID_Set.sizePolicy().hasHeightForWidth())
        self.pButton_PID_Set.setSizePolicy(sizePolicy)
        self.pButton_PID_Set.setObjectName("pButton_PID_Set")
        self.gridLayout_3.addWidget(self.pButton_PID_Set, 0, 0, 1, 1)
        self.cBox_PID = QtWidgets.QComboBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_PID.sizePolicy().hasHeightForWidth())
        self.cBox_PID.setSizePolicy(sizePolicy)
        self.cBox_PID.setObjectName("cBox_PID")
        self.gridLayout_3.addWidget(self.cBox_PID, 0, 1, 1, 1)
        self.label_Cycling_Time = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Cycling_Time.sizePolicy().hasHeightForWidth())
        self.label_Cycling_Time.setSizePolicy(sizePolicy)
        self.label_Cycling_Time.setObjectName("label_Cycling_Time")
        self.gridLayout_3.addWidget(self.label_Cycling_Time, 1, 0, 1, 1)
        self.spinBox_Cycling_Time = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Cycling_Time.sizePolicy().hasHeightForWidth())
        self.spinBox_Cycling_Time.setSizePolicy(sizePolicy)
        self.spinBox_Cycling_Time.setMinimum(1)
        self.spinBox_Cycling_Time.setMaximum(1000)
        self.spinBox_Cycling_Time.setProperty("value", 50)
        self.spinBox_Cycling_Time.setObjectName("spinBox_Cycling_Time")
        self.gridLayout_3.addWidget(self.spinBox_Cycling_Time, 1, 1, 1, 1)
        self.label_P_Share = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_P_Share.sizePolicy().hasHeightForWidth())
        self.label_P_Share.setSizePolicy(sizePolicy)
        self.label_P_Share.setObjectName("label_P_Share")
        self.gridLayout_3.addWidget(self.label_P_Share, 2, 0, 1, 1)
        self.spinBox_P_Share = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_P_Share.sizePolicy().hasHeightForWidth())
        self.spinBox_P_Share.setSizePolicy(sizePolicy)
        self.spinBox_P_Share.setMaximum(100000)
        self.spinBox_P_Share.setProperty("value", 1000)
        self.spinBox_P_Share.setObjectName("spinBox_P_Share")
        self.gridLayout_3.addWidget(self.spinBox_P_Share, 2, 1, 1, 1)
        self.label_I_Share = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_I_Share.sizePolicy().hasHeightForWidth())
        self.label_I_Share.setSizePolicy(sizePolicy)
        self.label_I_Share.setObjectName("label_I_Share")
        self.gridLayout_3.addWidget(self.label_I_Share, 3, 0, 1, 1)
        self.spinBox_I_Share = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_I_Share.sizePolicy().hasHeightForWidth())
        self.spinBox_I_Share.setSizePolicy(sizePolicy)
        self.spinBox_I_Share.setMaximum(100000)
        self.spinBox_I_Share.setSingleStep(0)
        self.spinBox_I_Share.setProperty("value", 200)
        self.spinBox_I_Share.setObjectName("spinBox_I_Share")
        self.gridLayout_3.addWidget(self.spinBox_I_Share, 3, 1, 1, 1)
        self.label_D_Share = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D_Share.sizePolicy().hasHeightForWidth())
        self.label_D_Share.setSizePolicy(sizePolicy)
        self.label_D_Share.setObjectName("label_D_Share")
        self.gridLayout_3.addWidget(self.label_D_Share, 4, 0, 1, 1)
        self.spinBox_D_Share = QtWidgets.QSpinBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_D_Share.sizePolicy().hasHeightForWidth())
        self.spinBox_D_Share.setSizePolicy(sizePolicy)
        self.spinBox_D_Share.setMaximum(100000)
        self.spinBox_D_Share.setProperty("value", 100)
        self.spinBox_D_Share.setObjectName("spinBox_D_Share")
        self.gridLayout_3.addWidget(self.spinBox_D_Share, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 7, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cBox_sampling_time = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_sampling_time.setObjectName("cBox_sampling_time")
        self.gridLayout_5.addWidget(self.cBox_sampling_time, 1, 0, 1, 1)
        self.sampling_time_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sampling_time_lbl.setObjectName("sampling_time_lbl")
        self.gridLayout_5.addWidget(self.sampling_time_lbl, 0, 0, 1, 1)
        self.time_lbl = QtWidgets.QLabel(self.centralwidget)
        self.time_lbl.setObjectName("time_lbl")
        self.gridLayout_5.addWidget(self.time_lbl, 2, 0, 1, 1)
        self.time_indicator = QtWidgets.QLabel(self.centralwidget)
        self.time_indicator.setObjectName("time_indicator")
        self.gridLayout_5.addWidget(self.time_indicator, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 5, 0, 1, 1)
        self.verticalLayout_plt = QtWidgets.QVBoxLayout()
        self.verticalLayout_plt.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_plt.setSpacing(6)
        self.verticalLayout_plt.setObjectName("verticalLayout_plt")
        self.groupBox_plt = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_plt.setTitle("")
        self.groupBox_plt.setObjectName("groupBox_plt")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_plt)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pltB = GraphicsLayoutWidget(self.groupBox_plt)
        self.pltB.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pltB.setFrameShape(QtWidgets.QFrame.Box)
        self.pltB.setObjectName("pltB")
        self.gridLayout_9.addWidget(self.pltB, 0, 0, 1, 1)
        self.pltD = GraphicsLayoutWidget(self.groupBox_plt)
        self.pltD.setFrameShape(QtWidgets.QFrame.Box)
        self.pltD.setObjectName("pltD")
        self.gridLayout_9.addWidget(self.pltD, 1, 0, 1, 1)
        self.plt = GraphicsLayoutWidget(self.groupBox_plt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt.sizePolicy().hasHeightForWidth())
        self.plt.setSizePolicy(sizePolicy)
        self.plt.setAutoFillBackground(False)
        self.plt.setFrameShape(QtWidgets.QFrame.Box)
        self.plt.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plt.setLineWidth(1)
        self.plt.setObjectName("plt")
        self.gridLayout_9.addWidget(self.plt, 2, 0, 1, 1)
        self.verticalLayout_plt.addWidget(self.groupBox_plt)
        self.gridLayout_2.addLayout(self.verticalLayout_plt, 0, 1, 10, 1)
        self.gridLayout_D = QtWidgets.QGridLayout()
        self.gridLayout_D.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_D.setObjectName("gridLayout_D")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioBtn_F0 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F0.sizePolicy().hasHeightForWidth())
        self.radioBtn_F0.setSizePolicy(sizePolicy)
        self.radioBtn_F0.setAutoExclusive(False)
        self.radioBtn_F0.setObjectName("radioBtn_F0")
        self.horizontalLayout_2.addWidget(self.radioBtn_F0)
        self.radioBtn_F3 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F3.sizePolicy().hasHeightForWidth())
        self.radioBtn_F3.setSizePolicy(sizePolicy)
        self.radioBtn_F3.setAutoExclusive(False)
        self.radioBtn_F3.setObjectName("radioBtn_F3")
        self.horizontalLayout_2.addWidget(self.radioBtn_F3)
        self.radioBtn_F5 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F5.sizePolicy().hasHeightForWidth())
        self.radioBtn_F5.setSizePolicy(sizePolicy)
        self.radioBtn_F5.setAutoExclusive(False)
        self.radioBtn_F5.setObjectName("radioBtn_F5")
        self.horizontalLayout_2.addWidget(self.radioBtn_F5)
        self.radioBtn_F7 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F7.sizePolicy().hasHeightForWidth())
        self.radioBtn_F7.setSizePolicy(sizePolicy)
        self.radioBtn_F7.setAutoExclusive(False)
        self.radioBtn_F7.setObjectName("radioBtn_F7")
        self.horizontalLayout_2.addWidget(self.radioBtn_F7)
        self.radioBtn_F9 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F9.sizePolicy().hasHeightForWidth())
        self.radioBtn_F9.setSizePolicy(sizePolicy)
        self.radioBtn_F9.setAutoExclusive(False)
        self.radioBtn_F9.setObjectName("radioBtn_F9")
        self.horizontalLayout_2.addWidget(self.radioBtn_F9)
        self.gridLayout_D.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_D.addWidget(self.line_2, 3, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout_D, 4, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pButton_Reference = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Reference.sizePolicy().hasHeightForWidth())
        self.pButton_Reference.setSizePolicy(sizePolicy)
        self.pButton_Reference.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Reference.setObjectName("pButton_Reference")
        self.horizontalLayout.addWidget(self.pButton_Reference)
        self.pButton_Reference_Not = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Reference_Not.sizePolicy().hasHeightForWidth())
        self.pButton_Reference_Not.setSizePolicy(sizePolicy)
        self.pButton_Reference_Not.setObjectName("pButton_Reference_Not")
        self.horizontalLayout.addWidget(self.pButton_Reference_Not)
        self.pButton_Clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Clear.sizePolicy().hasHeightForWidth())
        self.pButton_Clear.setSizePolicy(sizePolicy)
        self.pButton_Clear.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Clear.setObjectName("pButton_Clear")
        self.horizontalLayout.addWidget(self.pButton_Clear)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pButton_Start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Start.sizePolicy().hasHeightForWidth())
        self.pButton_Start.setSizePolicy(sizePolicy)
        self.pButton_Start.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Start.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 142, 192);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 128, 173);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(120, 120, 120);\n"
"}")
        self.pButton_Start.setObjectName("pButton_Start")
        self.horizontalLayout.addWidget(self.pButton_Start)
        self.pButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Stop.sizePolicy().hasHeightForWidth())
        self.pButton_Stop.setSizePolicy(sizePolicy)
        self.pButton_Stop.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Stop.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 142, 192);\n"
"    color: white;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 128, 173);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgb(200, 200, 200);\n"
"    color: rgb(120, 120, 120);\n"
"}")
        self.pButton_Stop.setObjectName("pButton_Stop")
        self.horizontalLayout.addWidget(self.pButton_Stop)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.horizontalLayout, 11, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.infostatus = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infostatus.sizePolicy().hasHeightForWidth())
        self.infostatus.setSizePolicy(sizePolicy)
        self.infostatus.setMinimumSize(QtCore.QSize(250, 0))
        self.infostatus.setObjectName("infostatus")
        self.verticalLayout.addWidget(self.infostatus)
        self.gridLayout_2.addLayout(self.verticalLayout, 11, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.cBox_Speed = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_Speed.sizePolicy().hasHeightForWidth())
        self.cBox_Speed.setSizePolicy(sizePolicy)
        self.cBox_Speed.setEditable(False)
        self.cBox_Speed.setObjectName("cBox_Speed")
        self.gridLayout.addWidget(self.cBox_Speed, 5, 0, 1, 2)
        self.cBox_Port = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_Port.sizePolicy().hasHeightForWidth())
        self.cBox_Port.setSizePolicy(sizePolicy)
        self.cBox_Port.setEditable(False)
        self.cBox_Port.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.cBox_Port.setObjectName("cBox_Port")
        self.gridLayout.addWidget(self.cBox_Port, 1, 0, 1, 2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 6, 0, 1, 2)
        self.cBox_Source = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_Source.sizePolicy().hasHeightForWidth())
        self.cBox_Source.setSizePolicy(sizePolicy)
        self.cBox_Source.setObjectName("cBox_Source")
        self.gridLayout.addWidget(self.cBox_Source, 3, 0, 1, 2)
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2.sizePolicy().hasHeightForWidth())
        self.l2.setSizePolicy(sizePolicy)
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 4, 0, 1, 2)
        self.info11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info11.sizePolicy().hasHeightForWidth())
        self.info11.setSizePolicy(sizePolicy)
        self.info11.setObjectName("info11")
        self.gridLayout.addWidget(self.info11, 2, 0, 1, 2)
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1.sizePolicy().hasHeightForWidth())
        self.l1.setSizePolicy(sizePolicy)
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 0, 0, 1, 1)
        self.label_COM_status = QtWidgets.QLabel(self.centralwidget)
        self.label_COM_status.setText("")
        self.label_COM_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_COM_status.setObjectName("label_COM_status")
        self.gridLayout.addWidget(self.label_COM_status, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.infobar = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infobar.sizePolicy().hasHeightForWidth())
        self.infobar.setSizePolicy(sizePolicy)
        self.infobar.setMinimumSize(QtCore.QSize(250, 0))
        self.infobar.setScaledContents(False)
        self.infobar.setObjectName("infobar")
        self.gridLayout_2.addWidget(self.infobar, 10, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 24))
        self.menuBar.setObjectName("menuBar")
        self.mainMenu = QtWidgets.QMenu(self.menuBar)
        self.mainMenu.setObjectName("mainMenu")
        self.menuAdd_On = QtWidgets.QMenu(self.menuBar)
        self.menuAdd_On.setObjectName("menuAdd_On")
        MainWindow.setMenuBar(self.menuBar)
        self.action_Firmware = QtWidgets.QAction(MainWindow)
        self.action_Firmware.setObjectName("action_Firmware")
        self.actionFirmware = QtWidgets.QAction(MainWindow)
        self.actionFirmware.setObjectName("actionFirmware")
        self.actionSoftware = QtWidgets.QAction(MainWindow)
        self.actionSoftware.setObjectName("actionSoftware")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionTEC_current = QtWidgets.QAction(MainWindow)
        self.actionTEC_current.setObjectName("actionTEC_current")
        self.actionLog_Data = QtWidgets.QAction(MainWindow)
        self.actionLog_Data.setObjectName("actionLog_Data")
        self.actionRaw_Data = QtWidgets.QAction(MainWindow)
        self.actionRaw_Data.setObjectName("actionRaw_Data")
        self.mainMenu.addAction(self.actionFirmware)
        self.mainMenu.addAction(self.actionSoftware)
        self.mainMenu.addAction(self.actionHelp)
        self.menuAdd_On.addAction(self.actionTEC_current)
        self.menuAdd_On.addAction(self.actionLog_Data)
        self.menuAdd_On.addAction(self.actionRaw_Data)
        self.menuBar.addAction(self.mainMenu.menuAction())
        self.menuBar.addAction(self.menuAdd_On.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openQCM NEXT - version 0.1.6 DEVELOPMENT"))
        self.groupBox_data.setTitle(_translate("MainWindow", "Frequency (Hz) - Dissipation (ppm)"))
        self.F9.setText(_translate("MainWindow", "0"))
        self.D7.setText(_translate("MainWindow", "0"))
        self.D5.setText(_translate("MainWindow", "0"))
        self.D9.setText(_translate("MainWindow", "0"))
        self.label_D5.setText(_translate("MainWindow", "D 5"))
        self.label_D7.setText(_translate("MainWindow", "D 7"))
        self.label_D9.setText(_translate("MainWindow", "D 9"))
        self.label_D0.setText(_translate("MainWindow", "D 0"))
        self.F3.setText(_translate("MainWindow", "0"))
        self.F0.setText(_translate("MainWindow", "0"))
        self.label_F5.setText(_translate("MainWindow", "F 5"))
        self.D3.setText(_translate("MainWindow", "0"))
        self.label_D3.setText(_translate("MainWindow", "D 3"))
        self.label_F0.setText(_translate("MainWindow", "F 0"))
        self.label_F3.setText(_translate("MainWindow", "F 3"))
        self.F5.setText(_translate("MainWindow", "0"))
        self.label_F7.setText(_translate("MainWindow", "F 7"))
        self.label_F9.setText(_translate("MainWindow", "F 9"))
        self.F7.setText(_translate("MainWindow", "0"))
        self.D0.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:18pt; font-weight:600;\">openQCM N</span><span style=\" font-size:18pt; font-weight:600; color:#000000;\">EXT</span><br/>Quartz Crystal Microbalance </p></body></html>"))
        self.label_Temperature_state.setText(_translate("MainWindow", "Temperature Control"))
        self.indicator_temperature.setText(_translate("MainWindow", "0"))
        self.pButton_Temperature_Set.setText(_translate("MainWindow", "Temperature Set"))
        self.label_Temperature.setText(_translate("MainWindow", "Temperature (° C)"))
        self.pButton_Tswitch_ON.setText(_translate("MainWindow", "ON"))
        self.pButton_TEC_Reset.setText(_translate("MainWindow", "RESET"))
        self.pButton_Tswitch_OFF.setText(_translate("MainWindow", "OFF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Temperature Control"))
        self.pButton_PID_Set.setText(_translate("MainWindow", "PID Set"))
        self.label_Cycling_Time.setText(_translate("MainWindow", "Cycling Time [msec]"))
        self.label_P_Share.setText(_translate("MainWindow", "P Share [mA/K]"))
        self.label_I_Share.setText(_translate("MainWindow", "I Share [mA/(K*sec)]"))
        self.label_D_Share.setText(_translate("MainWindow", "D Share [(mA*s)/K]"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "PID Control"))
        self.sampling_time_lbl.setText(_translate("MainWindow", "Datalog Sampling Time (sec) "))
        self.time_lbl.setText(_translate("MainWindow", "Time elapsed (sec)"))
        self.time_indicator.setText(_translate("MainWindow", "0"))
        self.radioBtn_F0.setText(_translate("MainWindow", "0th"))
        self.radioBtn_F3.setText(_translate("MainWindow", "3rd"))
        self.radioBtn_F5.setText(_translate("MainWindow", "5th"))
        self.radioBtn_F7.setText(_translate("MainWindow", "7th"))
        self.radioBtn_F9.setText(_translate("MainWindow", "9th"))
        self.pButton_Reference.setText(_translate("MainWindow", "Set Reference"))
        self.pButton_Reference_Not.setText(_translate("MainWindow", "Clear Reference "))
        self.pButton_Clear.setText(_translate("MainWindow", "Clear Plots"))
        self.pButton_Start.setText(_translate("MainWindow", "Start"))
        self.pButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.infostatus.setText(_translate("MainWindow", "Program status "))
        self.l2.setText(_translate("MainWindow", "Frequency (single mode)"))
        self.info11.setText(_translate("MainWindow", "Operation mode"))
        self.l1.setText(_translate("MainWindow", "Serial COM Port"))
        self.infobar.setText(_translate("MainWindow", "Infobar"))
        self.mainMenu.setTitle(_translate("MainWindow", "Info"))
        self.menuAdd_On.setTitle(_translate("MainWindow", "Add-On"))
        self.action_Firmware.setText(_translate("MainWindow", "&Firmware"))
        self.actionFirmware.setText(_translate("MainWindow", "Firmware Info"))
        self.actionSoftware.setText(_translate("MainWindow", "Software Info"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionTEC_current.setText(_translate("MainWindow", "Tec Current"))
        self.actionLog_Data.setText(_translate("MainWindow", "Log Data"))
        self.actionRaw_Data.setText(_translate("MainWindow", "Raw Data"))

from pyqtgraph import GraphicsLayoutWidget
