# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow_new.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1095)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("favicon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pButton_Start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Start.sizePolicy().hasHeightForWidth())
        self.pButton_Start.setSizePolicy(sizePolicy)
        self.pButton_Start.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Start.setObjectName("pButton_Start")
        self.horizontalLayout.addWidget(self.pButton_Start)
        self.pButton_Stop = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Stop.sizePolicy().hasHeightForWidth())
        self.pButton_Stop.setSizePolicy(sizePolicy)
        self.pButton_Stop.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Stop.setObjectName("pButton_Stop")
        self.horizontalLayout.addWidget(self.pButton_Stop)
        self.pButton_Reference = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Reference.sizePolicy().hasHeightForWidth())
        self.pButton_Reference.setSizePolicy(sizePolicy)
        self.pButton_Reference.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Reference.setObjectName("pButton_Reference")
        self.horizontalLayout.addWidget(self.pButton_Reference)
        self.pButton_Reference_Not = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Reference_Not.sizePolicy().hasHeightForWidth())
        self.pButton_Reference_Not.setSizePolicy(sizePolicy)
        self.pButton_Reference_Not.setObjectName("pButton_Reference_Not")
        self.horizontalLayout.addWidget(self.pButton_Reference_Not)
        self.pButton_Clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Clear.sizePolicy().hasHeightForWidth())
        self.pButton_Clear.setSizePolicy(sizePolicy)
        self.pButton_Clear.setMinimumSize(QtCore.QSize(0, 0))
        self.pButton_Clear.setObjectName("pButton_Clear")
        self.horizontalLayout.addWidget(self.pButton_Clear)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.gridLayout_2.addLayout(self.horizontalLayout, 9, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l1.sizePolicy().hasHeightForWidth())
        self.l1.setSizePolicy(sizePolicy)
        self.l1.setObjectName("l1")
        self.gridLayout.addWidget(self.l1, 0, 0, 1, 1)
        self.spinBox_Cycling_Time = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Cycling_Time.sizePolicy().hasHeightForWidth())
        self.spinBox_Cycling_Time.setSizePolicy(sizePolicy)
        self.spinBox_Cycling_Time.setMinimum(1)
        self.spinBox_Cycling_Time.setMaximum(1000)
        self.spinBox_Cycling_Time.setProperty("value", 50)
        self.spinBox_Cycling_Time.setObjectName("spinBox_Cycling_Time")
        self.gridLayout.addWidget(self.spinBox_Cycling_Time, 8, 1, 1, 1)
        self.label_Cycling_Time = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Cycling_Time.sizePolicy().hasHeightForWidth())
        self.label_Cycling_Time.setSizePolicy(sizePolicy)
        self.label_Cycling_Time.setObjectName("label_Cycling_Time")
        self.gridLayout.addWidget(self.label_Cycling_Time, 8, 0, 1, 1)
        self.pButton_Tswitch_ON = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Tswitch_ON.sizePolicy().hasHeightForWidth())
        self.pButton_Tswitch_ON.setSizePolicy(sizePolicy)
        self.pButton_Tswitch_ON.setObjectName("pButton_Tswitch_ON")
        self.gridLayout.addWidget(self.pButton_Tswitch_ON, 5, 0, 1, 1)
        self.label_Temperature_state = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Temperature_state.sizePolicy().hasHeightForWidth())
        self.label_Temperature_state.setSizePolicy(sizePolicy)
        self.label_Temperature_state.setObjectName("label_Temperature_state")
        self.gridLayout.addWidget(self.label_Temperature_state, 4, 0, 1, 2)
        self.info11 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info11.sizePolicy().hasHeightForWidth())
        self.info11.setSizePolicy(sizePolicy)
        self.info11.setObjectName("info11")
        self.gridLayout.addWidget(self.info11, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 2)
        self.label_D_Share = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D_Share.sizePolicy().hasHeightForWidth())
        self.label_D_Share.setSizePolicy(sizePolicy)
        self.label_D_Share.setObjectName("label_D_Share")
        self.gridLayout.addWidget(self.label_D_Share, 11, 0, 1, 1)
        self.pButton_Temperature_Set = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Temperature_Set.sizePolicy().hasHeightForWidth())
        self.pButton_Temperature_Set.setSizePolicy(sizePolicy)
        self.pButton_Temperature_Set.setObjectName("pButton_Temperature_Set")
        self.gridLayout.addWidget(self.pButton_Temperature_Set, 12, 0, 1, 1)
        self.label_Temperature = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Temperature.sizePolicy().hasHeightForWidth())
        self.label_Temperature.setSizePolicy(sizePolicy)
        self.label_Temperature.setObjectName("label_Temperature")
        self.gridLayout.addWidget(self.label_Temperature, 13, 0, 1, 1)
        self.label_I_Share = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_I_Share.sizePolicy().hasHeightForWidth())
        self.label_I_Share.setSizePolicy(sizePolicy)
        self.label_I_Share.setObjectName("label_I_Share")
        self.gridLayout.addWidget(self.label_I_Share, 10, 0, 1, 1)
        self.spinBox_D_Share = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_D_Share.sizePolicy().hasHeightForWidth())
        self.spinBox_D_Share.setSizePolicy(sizePolicy)
        self.spinBox_D_Share.setMaximum(100000)
        self.spinBox_D_Share.setProperty("value", 100)
        self.spinBox_D_Share.setObjectName("spinBox_D_Share")
        self.gridLayout.addWidget(self.spinBox_D_Share, 11, 1, 1, 1)
        self.doubleSpinBox_Temperature = QtWidgets.QDoubleSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_Temperature.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_Temperature.setSizePolicy(sizePolicy)
        self.doubleSpinBox_Temperature.setDecimals(0)
        self.doubleSpinBox_Temperature.setMinimum(5.0)
        self.doubleSpinBox_Temperature.setMaximum(45.0)
        self.doubleSpinBox_Temperature.setProperty("value", 25.0)
        self.doubleSpinBox_Temperature.setObjectName("doubleSpinBox_Temperature")
        self.gridLayout.addWidget(self.doubleSpinBox_Temperature, 12, 1, 1, 1)
        self.pButton_Tswitch_OFF = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_Tswitch_OFF.sizePolicy().hasHeightForWidth())
        self.pButton_Tswitch_OFF.setSizePolicy(sizePolicy)
        self.pButton_Tswitch_OFF.setObjectName("pButton_Tswitch_OFF")
        self.gridLayout.addWidget(self.pButton_Tswitch_OFF, 5, 1, 1, 1)
        self.spinBox_I_Share = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_I_Share.sizePolicy().hasHeightForWidth())
        self.spinBox_I_Share.setSizePolicy(sizePolicy)
        self.spinBox_I_Share.setMaximum(100000)
        self.spinBox_I_Share.setSingleStep(0)
        self.spinBox_I_Share.setProperty("value", 200)
        self.spinBox_I_Share.setObjectName("spinBox_I_Share")
        self.gridLayout.addWidget(self.spinBox_I_Share, 10, 1, 1, 1)
        self.indicator_temperature = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.indicator_temperature.sizePolicy().hasHeightForWidth())
        self.indicator_temperature.setSizePolicy(sizePolicy)
        self.indicator_temperature.setObjectName("indicator_temperature")
        self.gridLayout.addWidget(self.indicator_temperature, 13, 1, 1, 1)
        self.cBox_Port = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_Port.sizePolicy().hasHeightForWidth())
        self.cBox_Port.setSizePolicy(sizePolicy)
        self.cBox_Port.setEditable(True)
        self.cBox_Port.setObjectName("cBox_Port")
        self.gridLayout.addWidget(self.cBox_Port, 0, 1, 1, 1)
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l2.sizePolicy().hasHeightForWidth())
        self.l2.setSizePolicy(sizePolicy)
        self.l2.setObjectName("l2")
        self.gridLayout.addWidget(self.l2, 2, 0, 1, 1)
        self.cBox_Source = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_Source.sizePolicy().hasHeightForWidth())
        self.cBox_Source.setSizePolicy(sizePolicy)
        self.cBox_Source.setObjectName("cBox_Source")
        self.gridLayout.addWidget(self.cBox_Source, 1, 1, 1, 1)
        self.cBox_PID = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_PID.sizePolicy().hasHeightForWidth())
        self.cBox_PID.setSizePolicy(sizePolicy)
        self.cBox_PID.setObjectName("cBox_PID")
        self.gridLayout.addWidget(self.cBox_PID, 7, 1, 1, 1)
        self.pButton_PID_Set = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_PID_Set.sizePolicy().hasHeightForWidth())
        self.pButton_PID_Set.setSizePolicy(sizePolicy)
        self.pButton_PID_Set.setObjectName("pButton_PID_Set")
        self.gridLayout.addWidget(self.pButton_PID_Set, 7, 0, 1, 1)
        self.spinBox_P_Share = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_P_Share.sizePolicy().hasHeightForWidth())
        self.spinBox_P_Share.setSizePolicy(sizePolicy)
        self.spinBox_P_Share.setMaximum(100000)
        self.spinBox_P_Share.setProperty("value", 1000)
        self.spinBox_P_Share.setObjectName("spinBox_P_Share")
        self.gridLayout.addWidget(self.spinBox_P_Share, 9, 1, 1, 1)
        self.cBox_Speed = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBox_Speed.sizePolicy().hasHeightForWidth())
        self.cBox_Speed.setSizePolicy(sizePolicy)
        self.cBox_Speed.setEditable(True)
        self.cBox_Speed.setObjectName("cBox_Speed")
        self.gridLayout.addWidget(self.cBox_Speed, 2, 1, 1, 1)
        self.label_P_Share = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_P_Share.sizePolicy().hasHeightForWidth())
        self.label_P_Share.setSizePolicy(sizePolicy)
        self.label_P_Share.setObjectName("label_P_Share")
        self.gridLayout.addWidget(self.label_P_Share, 9, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 14, 0, 1, 2)
        self.pButton_TEC_Reset = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_TEC_Reset.setObjectName("pButton_TEC_Reset")
        self.gridLayout.addWidget(self.pButton_TEC_Reset, 6, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.infobar = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infobar.sizePolicy().hasHeightForWidth())
        self.infobar.setSizePolicy(sizePolicy)
        self.infobar.setMinimumSize(QtCore.QSize(340, 0))
        self.infobar.setObjectName("infobar")
        self.verticalLayout.addWidget(self.infobar)
        self.infostatus = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infostatus.sizePolicy().hasHeightForWidth())
        self.infostatus.setSizePolicy(sizePolicy)
        self.infostatus.setMinimumSize(QtCore.QSize(340, 0))
        self.infostatus.setObjectName("infostatus")
        self.verticalLayout.addWidget(self.infostatus)
        self.gridLayout_2.addLayout(self.verticalLayout, 9, 0, 1, 1)
        self.logData_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logData_btn.setObjectName("logData_btn")
        self.gridLayout_2.addWidget(self.logData_btn, 6, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sampling_time_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sampling_time_lbl.setObjectName("sampling_time_lbl")
        self.gridLayout_5.addWidget(self.sampling_time_lbl, 0, 0, 1, 1)
        self.cBox_sampling_time = QtWidgets.QComboBox(self.centralwidget)
        self.cBox_sampling_time.setObjectName("cBox_sampling_time")
        self.gridLayout_5.addWidget(self.cBox_sampling_time, 0, 1, 1, 1)
        self.time_indicator = QtWidgets.QLabel(self.centralwidget)
        self.time_indicator.setObjectName("time_indicator")
        self.gridLayout_5.addWidget(self.time_indicator, 1, 1, 1, 1)
        self.time_lbl = QtWidgets.QLabel(self.centralwidget)
        self.time_lbl.setObjectName("time_lbl")
        self.gridLayout_5.addWidget(self.time_lbl, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.rawData_btn = QtWidgets.QPushButton(self.centralwidget)
        self.rawData_btn.setObjectName("rawData_btn")
        self.gridLayout_2.addWidget(self.rawData_btn, 7, 0, 1, 1)
        self.gridLayout_D = QtWidgets.QGridLayout()
        self.gridLayout_D.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_D.setObjectName("gridLayout_D")
        self.label_D9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D9.sizePolicy().hasHeightForWidth())
        self.label_D9.setSizePolicy(sizePolicy)
        self.label_D9.setObjectName("label_D9")
        self.gridLayout_D.addWidget(self.label_D9, 8, 0, 1, 1)
        self.D9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D9.sizePolicy().hasHeightForWidth())
        self.D9.setSizePolicy(sizePolicy)
        self.D9.setObjectName("D9")
        self.gridLayout_D.addWidget(self.D9, 8, 2, 1, 1)
        self.label_D5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D5.sizePolicy().hasHeightForWidth())
        self.label_D5.setSizePolicy(sizePolicy)
        self.label_D5.setTextFormat(QtCore.Qt.RichText)
        self.label_D5.setObjectName("label_D5")
        self.gridLayout_D.addWidget(self.label_D5, 6, 0, 1, 1)
        self.label_D7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D7.sizePolicy().hasHeightForWidth())
        self.label_D7.setSizePolicy(sizePolicy)
        self.label_D7.setTextFormat(QtCore.Qt.RichText)
        self.label_D7.setObjectName("label_D7")
        self.gridLayout_D.addWidget(self.label_D7, 7, 0, 1, 1)
        self.label_D3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D3.sizePolicy().hasHeightForWidth())
        self.label_D3.setSizePolicy(sizePolicy)
        self.label_D3.setTextFormat(QtCore.Qt.RichText)
        self.label_D3.setObjectName("label_D3")
        self.gridLayout_D.addWidget(self.label_D3, 5, 0, 1, 1)
        self.label_D0 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D0.sizePolicy().hasHeightForWidth())
        self.label_D0.setSizePolicy(sizePolicy)
        self.label_D0.setTextFormat(QtCore.Qt.RichText)
        self.label_D0.setObjectName("label_D0")
        self.gridLayout_D.addWidget(self.label_D0, 4, 0, 1, 1)
        self.label_D5_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D5_col.sizePolicy().hasHeightForWidth())
        self.label_D5_col.setSizePolicy(sizePolicy)
        self.label_D5_col.setText("")
        self.label_D5_col.setObjectName("label_D5_col")
        self.gridLayout_D.addWidget(self.label_D5_col, 6, 1, 1, 1)
        self.label_D3_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D3_col.sizePolicy().hasHeightForWidth())
        self.label_D3_col.setSizePolicy(sizePolicy)
        self.label_D3_col.setText("")
        self.label_D3_col.setObjectName("label_D3_col")
        self.gridLayout_D.addWidget(self.label_D3_col, 5, 1, 1, 1)
        self.D3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3.sizePolicy().hasHeightForWidth())
        self.D3.setSizePolicy(sizePolicy)
        self.D3.setObjectName("D3")
        self.gridLayout_D.addWidget(self.D3, 5, 2, 1, 1)
        self.D7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7.sizePolicy().hasHeightForWidth())
        self.D7.setSizePolicy(sizePolicy)
        self.D7.setObjectName("D7")
        self.gridLayout_D.addWidget(self.D7, 7, 2, 1, 1)
        self.label_D0_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D0_col.sizePolicy().hasHeightForWidth())
        self.label_D0_col.setSizePolicy(sizePolicy)
        self.label_D0_col.setText("")
        self.label_D0_col.setObjectName("label_D0_col")
        self.gridLayout_D.addWidget(self.label_D0_col, 4, 1, 1, 1)
        self.D5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5.sizePolicy().hasHeightForWidth())
        self.D5.setSizePolicy(sizePolicy)
        self.D5.setObjectName("D5")
        self.gridLayout_D.addWidget(self.D5, 6, 2, 1, 1)
        self.label_D7_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D7_col.sizePolicy().hasHeightForWidth())
        self.label_D7_col.setSizePolicy(sizePolicy)
        self.label_D7_col.setText("")
        self.label_D7_col.setObjectName("label_D7_col")
        self.gridLayout_D.addWidget(self.label_D7_col, 7, 1, 1, 1)
        self.label_D9_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D9_col.sizePolicy().hasHeightForWidth())
        self.label_D9_col.setSizePolicy(sizePolicy)
        self.label_D9_col.setText("")
        self.label_D9_col.setObjectName("label_D9_col")
        self.gridLayout_D.addWidget(self.label_D9_col, 8, 1, 1, 1)
        self.label_D_Title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_D_Title.sizePolicy().hasHeightForWidth())
        self.label_D_Title.setSizePolicy(sizePolicy)
        self.label_D_Title.setObjectName("label_D_Title")
        self.gridLayout_D.addWidget(self.label_D_Title, 3, 0, 1, 3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioBtn_F0 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F0.sizePolicy().hasHeightForWidth())
        self.radioBtn_F0.setSizePolicy(sizePolicy)
        self.radioBtn_F0.setAutoExclusive(False)
        self.radioBtn_F0.setObjectName("radioBtn_F0")
        self.horizontalLayout_2.addWidget(self.radioBtn_F0)
        self.radioBtn_F3 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F3.sizePolicy().hasHeightForWidth())
        self.radioBtn_F3.setSizePolicy(sizePolicy)
        self.radioBtn_F3.setAutoExclusive(False)
        self.radioBtn_F3.setObjectName("radioBtn_F3")
        self.horizontalLayout_2.addWidget(self.radioBtn_F3)
        self.radioBtn_F5 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F5.sizePolicy().hasHeightForWidth())
        self.radioBtn_F5.setSizePolicy(sizePolicy)
        self.radioBtn_F5.setAutoExclusive(False)
        self.radioBtn_F5.setObjectName("radioBtn_F5")
        self.horizontalLayout_2.addWidget(self.radioBtn_F5)
        self.radioBtn_F7 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F7.sizePolicy().hasHeightForWidth())
        self.radioBtn_F7.setSizePolicy(sizePolicy)
        self.radioBtn_F7.setAutoExclusive(False)
        self.radioBtn_F7.setObjectName("radioBtn_F7")
        self.horizontalLayout_2.addWidget(self.radioBtn_F7)
        self.radioBtn_F9 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioBtn_F9.sizePolicy().hasHeightForWidth())
        self.radioBtn_F9.setSizePolicy(sizePolicy)
        self.radioBtn_F9.setAutoExclusive(False)
        self.radioBtn_F9.setObjectName("radioBtn_F9")
        self.horizontalLayout_2.addWidget(self.radioBtn_F9)
        self.gridLayout_D.addLayout(self.horizontalLayout_2, 10, 0, 1, 3)
        self.D0 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D0.sizePolicy().hasHeightForWidth())
        self.D0.setSizePolicy(sizePolicy)
        self.D0.setObjectName("D0")
        self.gridLayout_D.addWidget(self.D0, 4, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_D.addWidget(self.line_2, 9, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout_D, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.gridLayout_F = QtWidgets.QGridLayout()
        self.gridLayout_F.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_F.setObjectName("gridLayout_F")
        self.label_F0_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F0_col.sizePolicy().hasHeightForWidth())
        self.label_F0_col.setSizePolicy(sizePolicy)
        self.label_F0_col.setText("")
        self.label_F0_col.setObjectName("label_F0_col")
        self.gridLayout_F.addWidget(self.label_F0_col, 1, 1, 1, 1)
        self.label_F5_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F5_col.sizePolicy().hasHeightForWidth())
        self.label_F5_col.setSizePolicy(sizePolicy)
        self.label_F5_col.setText("")
        self.label_F5_col.setObjectName("label_F5_col")
        self.gridLayout_F.addWidget(self.label_F5_col, 3, 1, 1, 1)
        self.F7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F7.sizePolicy().hasHeightForWidth())
        self.F7.setSizePolicy(sizePolicy)
        self.F7.setObjectName("F7")
        self.gridLayout_F.addWidget(self.F7, 4, 2, 1, 1)
        self.label_F5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F5.sizePolicy().hasHeightForWidth())
        self.label_F5.setSizePolicy(sizePolicy)
        self.label_F5.setTextFormat(QtCore.Qt.RichText)
        self.label_F5.setObjectName("label_F5")
        self.gridLayout_F.addWidget(self.label_F5, 3, 0, 1, 1)
        self.label_F3_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F3_col.sizePolicy().hasHeightForWidth())
        self.label_F3_col.setSizePolicy(sizePolicy)
        self.label_F3_col.setText("")
        self.label_F3_col.setObjectName("label_F3_col")
        self.gridLayout_F.addWidget(self.label_F3_col, 2, 1, 1, 1)
        self.label_F_Title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F_Title.sizePolicy().hasHeightForWidth())
        self.label_F_Title.setSizePolicy(sizePolicy)
        self.label_F_Title.setObjectName("label_F_Title")
        self.gridLayout_F.addWidget(self.label_F_Title, 0, 0, 1, 3)
        self.F5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5.sizePolicy().hasHeightForWidth())
        self.F5.setSizePolicy(sizePolicy)
        self.F5.setObjectName("F5")
        self.gridLayout_F.addWidget(self.F5, 3, 2, 1, 1)
        self.F0 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F0.sizePolicy().hasHeightForWidth())
        self.F0.setSizePolicy(sizePolicy)
        self.F0.setObjectName("F0")
        self.gridLayout_F.addWidget(self.F0, 1, 2, 1, 1)
        self.label_F3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F3.sizePolicy().hasHeightForWidth())
        self.label_F3.setSizePolicy(sizePolicy)
        self.label_F3.setTextFormat(QtCore.Qt.RichText)
        self.label_F3.setObjectName("label_F3")
        self.gridLayout_F.addWidget(self.label_F3, 2, 0, 1, 1)
        self.label_F0 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F0.sizePolicy().hasHeightForWidth())
        self.label_F0.setSizePolicy(sizePolicy)
        self.label_F0.setTextFormat(QtCore.Qt.RichText)
        self.label_F0.setScaledContents(False)
        self.label_F0.setObjectName("label_F0")
        self.gridLayout_F.addWidget(self.label_F0, 1, 0, 1, 1)
        self.label_F9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F9.sizePolicy().hasHeightForWidth())
        self.label_F9.setSizePolicy(sizePolicy)
        self.label_F9.setTextFormat(QtCore.Qt.RichText)
        self.label_F9.setObjectName("label_F9")
        self.gridLayout_F.addWidget(self.label_F9, 5, 0, 1, 1)
        self.label_F9_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F9_col.sizePolicy().hasHeightForWidth())
        self.label_F9_col.setSizePolicy(sizePolicy)
        self.label_F9_col.setText("")
        self.label_F9_col.setObjectName("label_F9_col")
        self.gridLayout_F.addWidget(self.label_F9_col, 5, 1, 1, 1)
        self.F9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F9.sizePolicy().hasHeightForWidth())
        self.F9.setSizePolicy(sizePolicy)
        self.F9.setObjectName("F9")
        self.gridLayout_F.addWidget(self.F9, 5, 2, 1, 1)
        self.label_F7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F7.sizePolicy().hasHeightForWidth())
        self.label_F7.setSizePolicy(sizePolicy)
        self.label_F7.setTextFormat(QtCore.Qt.RichText)
        self.label_F7.setObjectName("label_F7")
        self.gridLayout_F.addWidget(self.label_F7, 4, 0, 1, 1)
        self.label_F7_col = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_F7_col.sizePolicy().hasHeightForWidth())
        self.label_F7_col.setSizePolicy(sizePolicy)
        self.label_F7_col.setText("")
        self.label_F7_col.setObjectName("label_F7_col")
        self.gridLayout_F.addWidget(self.label_F7_col, 4, 1, 1, 1)
        self.F3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3.sizePolicy().hasHeightForWidth())
        self.F3.setSizePolicy(sizePolicy)
        self.F3.setObjectName("F3")
        self.gridLayout_F.addWidget(self.F3, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_F, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pltB = GraphicsLayoutWidget(self.centralwidget)
        self.pltB.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pltB.setFrameShape(QtWidgets.QFrame.Box)
        self.pltB.setObjectName("pltB")
        self.verticalLayout_3.addWidget(self.pltB)
        self.pltD = GraphicsLayoutWidget(self.centralwidget)
        self.pltD.setFrameShape(QtWidgets.QFrame.Box)
        self.pltD.setObjectName("pltD")
        self.verticalLayout_3.addWidget(self.pltD)
        self.plt = GraphicsLayoutWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plt.sizePolicy().hasHeightForWidth())
        self.plt.setSizePolicy(sizePolicy)
        self.plt.setAutoFillBackground(False)
        self.plt.setFrameShape(QtWidgets.QFrame.Box)
        self.plt.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.plt.setLineWidth(1)
        self.plt.setObjectName("plt")
        self.verticalLayout_3.addWidget(self.plt)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 9, 1)
        self.pButtonSecondWindow = QtWidgets.QPushButton(self.centralwidget)
        self.pButtonSecondWindow.setObjectName("pButtonSecondWindow")
        self.gridLayout_2.addWidget(self.pButtonSecondWindow, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1200, 24))
        self.menuBar.setObjectName("menuBar")
        self.mainMenu = QtWidgets.QMenu(self.menuBar)
        self.mainMenu.setObjectName("mainMenu")
        MainWindow.setMenuBar(self.menuBar)
        self.action_Firmware = QtWidgets.QAction(MainWindow)
        self.action_Firmware.setObjectName("action_Firmware")
        self.actionFirmware = QtWidgets.QAction(MainWindow)
        self.actionFirmware.setObjectName("actionFirmware")
        self.actionSoftware = QtWidgets.QAction(MainWindow)
        self.actionSoftware.setObjectName("actionSoftware")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.mainMenu.addAction(self.actionFirmware)
        self.mainMenu.addAction(self.actionSoftware)
        self.mainMenu.addAction(self.actionHelp)
        self.menuBar.addAction(self.mainMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "openQCM NEXT - version 0.1.6 DEVELOPMENT"))
        self.pButton_Start.setText(_translate("MainWindow", "Start"))
        self.pButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.pButton_Reference.setText(_translate("MainWindow", "Set Reference"))
        self.pButton_Reference_Not.setText(_translate("MainWindow", "Reset Reference "))
        self.pButton_Clear.setText(_translate("MainWindow", "Clear Plots"))
        self.l1.setText(_translate("MainWindow", "Serial COM Port"))
        self.label_Cycling_Time.setText(_translate("MainWindow", "Cycling Time [msec]"))
        self.pButton_Tswitch_ON.setText(_translate("MainWindow", "Temperature Ctrl ON"))
        self.label_Temperature_state.setText(_translate("MainWindow", "Temperature Control"))
        self.info11.setText(_translate("MainWindow", "Operation mode"))
        self.label_D_Share.setText(_translate("MainWindow", "D Share [(mA*s)/K]"))
        self.pButton_Temperature_Set.setText(_translate("MainWindow", "Temperature Set"))
        self.label_Temperature.setText(_translate("MainWindow", "Temperature (° C)"))
        self.label_I_Share.setText(_translate("MainWindow", "I Share [mA/(K*sec)]"))
        self.pButton_Tswitch_OFF.setText(_translate("MainWindow", "Temperature Crtl OFF"))
        self.indicator_temperature.setText(_translate("MainWindow", "0"))
        self.l2.setText(_translate("MainWindow", "Frequency (single mode)"))
        self.pButton_PID_Set.setText(_translate("MainWindow", "PID Set"))
        self.label_P_Share.setText(_translate("MainWindow", "P Share [mA/K]"))
        self.pButton_TEC_Reset.setText(_translate("MainWindow", "TEC Controller RESET"))
        self.infobar.setText(_translate("MainWindow", "Infobar"))
        self.infostatus.setText(_translate("MainWindow", "Program status "))
        self.logData_btn.setText(_translate("MainWindow", "LOG DATA VIEW (BETA)"))
        self.sampling_time_lbl.setText(_translate("MainWindow", "Datalog Sampling Time (sec) "))
        self.time_indicator.setText(_translate("MainWindow", "0"))
        self.time_lbl.setText(_translate("MainWindow", "Time elapsed (sec)"))
        self.rawData_btn.setText(_translate("MainWindow", "RAW DATA VIEW (BETA)"))
        self.label_D9.setText(_translate("MainWindow", "D 9"))
        self.D9.setText(_translate("MainWindow", "0"))
        self.label_D5.setText(_translate("MainWindow", "D 5"))
        self.label_D7.setText(_translate("MainWindow", "D 7"))
        self.label_D3.setText(_translate("MainWindow", "D 3"))
        self.label_D0.setText(_translate("MainWindow", "D 0"))
        self.D3.setText(_translate("MainWindow", "0"))
        self.D7.setText(_translate("MainWindow", "0"))
        self.D5.setText(_translate("MainWindow", "0"))
        self.label_D_Title.setText(_translate("MainWindow", "Dissipation (ppm)"))
        self.radioBtn_F0.setText(_translate("MainWindow", "0th"))
        self.radioBtn_F3.setText(_translate("MainWindow", "3rd"))
        self.radioBtn_F5.setText(_translate("MainWindow", "5th"))
        self.radioBtn_F7.setText(_translate("MainWindow", "7th"))
        self.radioBtn_F9.setText(_translate("MainWindow", "9th"))
        self.D0.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "ADD-ON FEATURES (BETA)"))
        self.F7.setText(_translate("MainWindow", "0"))
        self.label_F5.setText(_translate("MainWindow", "F 5"))
        self.label_F_Title.setText(_translate("MainWindow", "Frequency (Hz)"))
        self.F5.setText(_translate("MainWindow", "0"))
        self.F0.setText(_translate("MainWindow", "0"))
        self.label_F3.setText(_translate("MainWindow", "F 3"))
        self.label_F0.setText(_translate("MainWindow", "F 0"))
        self.label_F9.setText(_translate("MainWindow", "F 9"))
        self.F9.setText(_translate("MainWindow", "0"))
        self.label_F7.setText(_translate("MainWindow", "F 7"))
        self.F3.setText(_translate("MainWindow", "0"))
        self.pButtonSecondWindow.setText(_translate("MainWindow", "TEC CURRENT MONITORING"))
        self.mainMenu.setTitle(_translate("MainWindow", "Info"))
        self.action_Firmware.setText(_translate("MainWindow", "&Firmware"))
        self.actionFirmware.setText(_translate("MainWindow", "Firmware Info"))
        self.actionSoftware.setText(_translate("MainWindow", "Software Info"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))

from pyqtgraph import GraphicsLayoutWidget
